package simpleshop.business;
dialect  "java"

/*
    Preload objects from database for validation.
*/

import simpleshop.dto.CartItem;
import simpleshop.domain.model.Product;
global simpleshop.data.ProductDAO productDAO;


rule "preloadCartItemProduct"
    salience 1000
    ruleflow-group "preload"
when
    CartItem($productId : productId != null)
    not Product(id == $productId)
    $product : Product() from productDAO.get($productId)
then
    insert($product);
end
