package simpleshop.business;
dialect  "java"

/*
    Rules that validates dto prior to process OR
    domain objects prior to saving.
*/

import simpleshop.domain.model.Product;
import simpleshop.dto.CartItem;
global simpleshop.data.ProductDAO productDAO;
global org.springframework.validation.Errors errors;


//////////////////////// DTO Validation ///////////////////////////
rule "cartItemShouldHaveValidProductId"
    salience 1000
    ruleflow-group "validation"
when
    CartItem($productId : productId != null)
    not Product(id == $productId)
then
    errors.reject("cartItem.productId", drools.getRule().getName());
end


//////////////////////// Domain Validation ///////////////////////////